-- SOURCE_EMPLOYEES table
SELECT * FROM SOURCE_EMPLOYEES ORDER by ID LIMIT 10;

SELECT COUNT(*) FROM SOURCE_EMPLOYEES;

-- TARGET_STUDENTS table
SELECT * FROM TARGET_STUDENTS ORDER by ID LIMIT 10;

SELECT COUNT(*) FROM TARGET_STUDENTS;

-- join `SOURCE_EMPLOYEES` with `TARGET_STUDENTS`
SELECT s.ID, s.FIRST_NAME as SOURCE_FIRST_NAME, t.FIRST_NAME as TARGET_FIRST_NAME, s.LAST_NAME as SOURCE_LAST_NAME, t.LAST_NAME as TARGET_LAST_NAME
FROM SOURCE_EMPLOYEES as s
INNER JOIN TARGET_STUDENTS as t
ON s.id=t.id
ORDER by id
LIMIT 10;
